In [26]:
print("Hello")

Hello


In [27]:
#Import numpy 
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [28]:
# to checking numpy version
print(np.__version__)

1.26.4


In [29]:
# to convert tuple into array
arr2=np.array((10,20,30,40,50,60,70,80,90,100))
print(arr2)

[ 10  20  30  40  50  60  70  80  90 100]


In [30]:
# zero dimensional array
arr=np.array(90)
print(arr)

90


In [31]:
# 1D array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [32]:
#2D array
arr1=np.array([[1,2],[3,4]])
print(arr1)

[[1 2]
 [3 4]]


In [33]:
#3D array
arr3=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(arr3)
# to find dimension of array
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [34]:
# to access element fron array
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [35]:
# to access 2D array
arr2=np.array([[100,200],
               [300,400]])
print(arr2)
print(arr2[0,0])
print(arr2[1,1])

[[100 200]
 [300 400]]
100
400


In [36]:
# to print negitive index element 
arr2=np.array([[[900,400,800],
                [500,600,700],
                [600,300,100]]])
print("3D Array :",arr2)
print(arr2[0,-2])
#print(arr2[1,-3])
              

3D Array : [[[900 400 800]
  [500 600 700]
  [600 300 100]]]
[500 600 700]


In [37]:
#sciling 
import numpy as np
arr=np.array([1,2,3,4,5,6,7,])
print(arr[1-4])

#Negative sciling
print(arr[-3:-1])

5
[5 6]


In [38]:
#to checking datatype
arr=np.array([90.5,90.7,67.5,90,4,99,10])
print("Array: ",arr)
print("Data type an array :",arr.dtype)

Array:  [90.5 90.7 67.5 90.   4.  99.  10. ]
Data type an array : float64


In [39]:
#shape
arr=np.array([[0,9,8,7,6,5,4,3,2,1],
             [0,9,8,7,6,5,4,3,2,1]])
print(arr)
print("Shape of an array :",arr.shape)

[[0 9 8 7 6 5 4 3 2 1]
 [0 9 8 7 6 5 4 3 2 1]]
Shape of an array : (2, 10)


In [40]:
#Size
arr=np.array([12,13,14,15,16])
print("Array: ",arr)
print("Size of array :",arr.size)

Array:  [12 13 14 15 16]
Size of array : 5


In [41]:
#Reshaping 
arrR=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
print(arrR)
a=arrR.reshape(4,3) ##here only take value witch can be arrange array's element like 3*4 =12 take only 12 element
print(a)

[ 10  20  30  40  50  60  70  80  90 100 110 120]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [42]:
#Iterating array element 
arr=np.array([20,30,40,50,60,70,80,90])
print("Array :",arr)
for i in arr:
    print(i)

Array : [20 30 40 50 60 70 80 90]
20
30
40
50
60
70
80
90


In [43]:
#Joining Array 
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
#arr3=np.concatenate((arr1,arr2))
arrr3=arr1+arr2
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [44]:
#Spiliting Array 
arr=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.array_split(arr,2)
print(a)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [45]:
#Searching Array
arr=np.array([12,13,14,15,16,17])
x=np.where(arr==14)
print(x)


(array([2], dtype=int64),)


In [46]:
#sorting Array

#Asending Array
arr1=np.array([6,7,8,9,10,1,2,3,4,5])
print("Asending :",np.sort(arr1))

#Desending 
print("Desending :",np.sort(arr1)[:: -1])

Asending : [ 1  2  3  4  5  6  7  8  9 10]
Desending : [10  9  8  7  6  5  4  3  2  1]


In [47]:
#Filter Array 
arr1=np.array([1,2,3,4,5])
x=[True,False,True,False,True]
a=arr1[x]
print(a)

[1 3 5]


In [57]:
#creating the filtering array 
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [50]:
#Data conversion 
arr=np.array([10,20,30,40,50,60,70])
print(arr.astype(float))


[10. 20. 30. 40. 50. 60. 70.]


In [51]:
#Append
arr=np.array([10,20,30,40,50,60,70])
print(np.append(arr,[6,7]))
print(np.append(arr,8))

#Insert 
#print(np.insert(arr,3[6,7]))

#deleting 
print(np.delete(arr,[1]))

[10 20 30 40 50 60 70  6  7]
[10 20 30 40 50 60 70  8]
[10 30 40 50 60 70]


In [52]:
#Aggregate Function 
arr=np.array([10,20,30,40,50,60,70])
print(arr)
#sum
print(np.sum(arr))
#min
print(np.min(arr))
#max
print(np.max(arr))
print(np.cumsum(arr))

[10 20 30 40 50 60 70]
280
10
70
[ 10  30  60 100 150 210 280]


In [53]:
import statistics as stats
arr=np.array([10,20,30,40,50,60,70,28,20])
a=np.array(arr)
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))

36.44444444444444
30.0
20
